name: cached_network_image_platform_interface_ce
description: Platform interface for CachedNetworkImage (Community Edition)
version: 5.2.0
homepage: https://github.com/blackstorm/flutter_cached_image
repository: https://github.com/blackstorm/flutter_cached_image/tree/develop/cached_network_image_platform_interface
topics:
  - cache
  - image
  - network-image

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
